language: node_js
node_js:
- '9'
before_script:
- yarn install
cache:
  yarn: true
script:
- yarn test --coverage
after_script:
- cat ./coverage/lcov.info | coveralls
branches:
  only:
  - master
env:
  global:
    secure: Bw9ItZewFAf+eEvrnGUt8LdQqxUcEdU58LS6VwCIZXfJIAByqQMauwciwqadQ0zM2CfLuoVar17IazJPasLedPuS6/vT1HAAVP7GKJdB+oMT+hKTONAVPALmxYnbo5ftb4IGB9wP3snO+gm350KIH87nr5Rc5lnchXdt2/fLZNQ7erOOaYIR/aIQQhM0wWNplwS8lny2JL+FNgz4JJUfSrC4PLXXy1lq51R5cD17Vt0EYQ/RIVJYL3EhEgJBlPwXRCQARQloavJ/RzhzB9erZKmkqEeJstoQZ8sHzv+jDg4tb0iq7qlTwFFsy/STPprKJiokfwBVPQOPPZrAdutv0w0XuyPeaYDUukQH7b8jEL0h0MLX3525e/8CByNyBiYn6aIIMHJqYzwU58jBVaMPu2LntP0B/cmhdnRsM7DUCFhIW9LsI4asRqmVXnktKTWyDekyQcO8pMkfpCbspAjPAwFY3LkHdcnrttYBjNL/y3UR7NWqq+LMKSCDp0aCdyg1Eb0xLBhlCT4L21qIIV189F1SAbW3elsmEUkZZVH5MEs0FU0w0PanK42ApatYxNvl2QCNRM9qBPYjKo32JuSFY35yXdsMH/6adzUxLXesLySElSf+495HeUmDki/AN8mnfnyyCIxDBLs2HBb7erqEWjA1zE+vlutWQeQiZLxekl4=
