language: node_js
node_js: 
  - "9"
before_script:
  - yarn install
cache:
  yarn: true
script:
  - yarn test
after_script:
  - "cat ./coverage/lcov.info | coveralls"
branches:
  only:
    - master
    - feature_test